"""
Document titles generated by a local LLM (MLX on Apple Silicon; default
Qwen2.5-7B-Instruct, 4-bit), in the style of the TANAP index titles.

Input per document: the series (context), the opening of its first scan and
the end of its last scan (place, date and signatures of a closing formula).
A few documents with a known TANAP title serve as examples in the prompt.
Output: one title per document, written to a JSONL file as it goes (resumable).

  uv run --with mlx-lm python -m segmentation titles-test     # test on documents with a known title
"""

import json
import logging
import os
import time

import pandas as pd

from .texts import TEXT_DIR

logger = logging.getLogger("segmentation")

MODEL = os.environ.get("SEGMENTATION_TITLE_MODEL", "mlx-community/Qwen2.5-7B-Instruct-4bit")
OPENING_CHARS, CLOSING_CHARS = 1500, 700
SYSTEM = (
    "Je bent archivaris van het archief van de Verenigde Oost-Indische Compagnie (VOC). "
    "Je krijgt de transcriptie (HTR, met fouten) van het begin en het einde van één archiefstuk. "
    "Schrijf één titel voor het stuk in de stijl van de inventaris (TANAP): de soort stuk (originele missive, copie missive, "
    "extract, resolutie, rapport, memorie, lijst, translaat, notitie, ...), de afzender en de geadresseerde met hun functie en "
    "standplaats, het onderwerp als dat kort te zeggen is, en de datum ('in dato 12 Maart 1741'). Neem namen over zoals ze in "
    "de tekst staan. Verzin niets dat niet in de tekst staat. Antwoord alleen met de titel, op één regel."
)

_texts: dict[str, pd.Series] = {}


def scan_text(filename: str) -> str:
    inv = filename.split("_")[2]
    if inv not in _texts:
        folder = os.path.join(TEXT_DIR, f"inv={inv}")
        _texts[inv] = pd.read_parquet(folder, columns=["filename", "text"]).set_index("filename")["text"] if os.path.isdir(folder) else pd.Series(dtype=str)
    return (_texts[inv].get(filename) or "").strip()


MONTHS_NL = "januari februari maart april mei juni juli augustus september oktober november december".split()


def document_date(first_scan: str, last_scan: str):
    """The document's own date: in the closing formula at the end of its last scan, or after 'dato' in its opening."""
    from .register_match import own_dates

    for fn in (last_scan, first_scan):
        ds = own_dates(scan_text(fn))
        if ds:
            return sorted(ds)[-1]
    return None


def document_input(first_scan: str, last_scan: str, series: str | None) -> str:
    first = scan_text(first_scan)
    opening = first[:OPENING_CHARS]
    if last_scan != first_scan:
        closing = scan_text(last_scan)[-CLOSING_CHARS:]
    else:  # one scan: its end, when the opening did not reach it (the closing formula: place, date, signatures)
        closing = first[max(OPENING_CHARS, len(first) - CLOSING_CHARS):] if len(first) > OPENING_CHARS else ""
    d = document_date(first_scan, last_scan)
    parts = []
    if series:
        parts.append(f"Serie: {series}")
    parts.append(f"Datum in de slotformule of aanhef: {d.day} {MONTHS_NL[d.month - 1]} {d.year}" if d else "Datum: niet gevonden in de slotformule")
    parts.append(f"Begin van het stuk:\n{opening}")
    if closing:
        parts.append(f"Einde van het stuk:\n{closing}")
    return "\n\n".join(parts)


def choose_examples(docs: pd.DataFrame, max_scans: int = 6) -> pd.DataFrame:
    """Examples for the prompt from documents with a known title: mostly letters (the bulk of the
    material), and a list, a resolution or extract, and a register or report."""
    d = docs[docs["n_scans"] <= max_scans].copy()
    t = d["title"].str.lower()
    groups = [
        (t.str.contains(r"^(originele?|origineele?)\s+(missive|brief)"), 1),
        (t.str.contains(r"^(copie|copia)\s+(missive|brief)"), 1),
        (t.str.contains(r"^(missive|brief|een brief|een missive)"), 1),
        (t.str.contains(r"^(lijst|lyst|notitie|specificatie|staat)"), 1),
        (t.str.contains(r"(resolutie|extract)"), 1),
        (t.str.contains(r"^(register|rapport|memorie)"), 1),
    ]
    picks = []
    for mask, k in groups:
        g = d[mask & ~d.index.isin([p for p in picks])]
        picks += list(g.sample(min(k, len(g)), random_state=0).index)
    return d.loc[picks]


def build_messages(doc_input: str, examples: list[tuple[str, str]]) -> list[dict]:
    msgs = [{"role": "system", "content": SYSTEM}]
    for inp, title in examples:
        msgs += [{"role": "user", "content": inp}, {"role": "assistant", "content": title}]
    msgs.append({"role": "user", "content": doc_input})
    return msgs


class TitleModel:
    """The LLM with the fixed part of the prompt (instructions and examples) computed once:
    for each document only its own text is processed (a copy of the prefix's KV cache)."""

    def __init__(self, examples: list[tuple[str, str]], model: str = MODEL):
        import mlx.core as mx
        from mlx_lm import load
        from mlx_lm.models.cache import make_prompt_cache

        self.model, self.tokenizer = load(model)
        prefix = build_messages("", examples)[:-1]
        self.prefix_ids = self.tokenizer.apply_chat_template(prefix, tokenize=True)
        self.examples = examples
        self.cache = make_prompt_cache(self.model)
        self.model(mx.array(self.prefix_ids)[None], cache=self.cache)
        mx.eval([c.state for c in self.cache])

    def title(self, doc_input: str, max_tokens: int = 90) -> str:
        import copy

        from mlx_lm import generate

        ids = self.tokenizer.apply_chat_template(build_messages(doc_input, self.examples), add_generation_prompt=True, tokenize=True)
        if ids[: len(self.prefix_ids)] != self.prefix_ids:  # the template did not reproduce the prefix: no reuse
            out = generate(self.model, self.tokenizer, prompt=ids, max_tokens=max_tokens)
        else:
            out = generate(self.model, self.tokenizer, prompt=ids[len(self.prefix_ids):], max_tokens=max_tokens, prompt_cache=copy.deepcopy(self.cache))
        return out.strip().splitlines()[0].strip().strip('"') if out.strip() else ""


def generate_titles(docs: pd.DataFrame, examples: list[tuple[str, str]], out_path: str, model: str = MODEL):
    """Titles for docs (columns key, first_scan, last_scan, series), appended to out_path (JSONL); keys already there are skipped."""
    done = set()
    if os.path.exists(out_path):
        with open(out_path) as f:
            done = {json.loads(line)["key"] for line in f if line.strip()}
    todo = docs[~docs["key"].isin(done)]
    logger.info("Titles: %d to do (%d already in %s)", len(todo), len(done), out_path)
    if todo.empty:
        return
    tm = TitleModel(examples, model)
    t0 = time.time()
    with open(out_path, "a") as f:
        for k, r in enumerate(todo.itertuples(), 1):
            inp = document_input(r.first_scan, r.last_scan, getattr(r, "series", None))
            title = tm.title(inp)
            f.write(json.dumps({"key": r.key, "title": title}, ensure_ascii=False) + "\n")
            f.flush()
            if k % 10 == 0 or k == len(todo):
                logger.info("  %d/%d titles (%.1fs each; about %.0f min to go)", k, len(todo), (time.time() - t0) / k, (time.time() - t0) / k * (len(todo) - k) / 60)
